# Generated by Django 3.0.7 on 2020-07-07 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_headlines', models.TextField()),
                ('country_content', models.TextField()),
                ('country_image_url', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CricketNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_headlines', models.TextField()),
                ('cricket_content', models.TextField()),
                ('cricket_image_url', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_lead_text', models.TextField()),
                ('ent_image_url', models.TextField()),
                ('ent_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_headlines', models.TextField()),
                ('latest_content', models.TextField()),
                ('latest_image_url', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_lead_text', models.TextField()),
                ('state_image_url', models.TextField()),
                ('state_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_headlines', models.TextField()),
                ('world_content', models.TextField()),
                ('world_image_url', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateOneliners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_liners', models.TextField()),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.StateNews')),
            ],
        ),
        migrations.CreateModel(
            name='EntOneliners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_liners', models.TextField()),
                ('ent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.EntNews')),
            ],
        ),
    ]
