# Generated by Django 3.0.7 on 2020-08-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='headline_image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NdtvNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndtv_headlines', models.TextField()),
                ('ndtv_content', models.TextField()),
                ('ndtv_img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll_headlines', models.TextField()),
                ('scroll_content', models.TextField()),
                ('scroll_img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZeeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zee_headlines', models.TextField()),
                ('zee_content', models.TextField()),
                ('zee_img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ZeeWorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ZeeNews')),
            ],
        ),
        migrations.CreateModel(
            name='ZeeLatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ZeeNews')),
            ],
        ),
        migrations.CreateModel(
            name='ZeeCricketNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ZeeNews')),
            ],
        ),
        migrations.CreateModel(
            name='ZeeCountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ZeeNews')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollWorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ScrollNews')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollLatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ScrollNews')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollEntNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ScrollNews')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCricketNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ScrollNews')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ScrollNews')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ScrollNews')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField()),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='NewsHeadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField()),
                ('headlines_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Headlines')),
            ],
        ),
        migrations.CreateModel(
            name='NdtvWorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NdtvNews')),
            ],
        ),
        migrations.CreateModel(
            name='NdtvLatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NdtvNews')),
            ],
        ),
        migrations.CreateModel(
            name='NdtvEntNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NdtvNews')),
            ],
        ),
        migrations.CreateModel(
            name='NdtvCricketNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NdtvNews')),
            ],
        ),
        migrations.CreateModel(
            name='NdtvCountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NdtvNews')),
            ],
        ),
        migrations.CreateModel(
            name='NdtvCityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NdtvNews')),
            ],
        ),
    ]
