# Generated by Django 3.0.7 on 2020-06-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestNewsItem',
            new_name='LatestNews',
        ),
    ]
