# Generated by Django 3.0.7 on 2020-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdtvCityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_headlines', models.TextField()),
                ('city_content', models.TextField()),
                ('city_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NdtvCountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_headlines', models.TextField()),
                ('country_content', models.TextField()),
                ('country_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NdtvCricketNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_headlines', models.TextField()),
                ('cricket_content', models.TextField()),
                ('cricket_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NdtvEntNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_headlines', models.TextField()),
                ('ent_content', models.TextField()),
                ('ent_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NdtvlatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_headlines', models.TextField()),
                ('latest_content', models.TextField()),
                ('latest_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NdtvWorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_headlines', models.TextField()),
                ('world_content', models.TextField()),
                ('world_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_headlines', models.TextField()),
                ('city_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_headlines', models.TextField()),
                ('country_content', models.TextField()),
                ('country_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollCricketNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricket_headlines', models.TextField()),
                ('cricket_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollEntNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_headlines', models.TextField()),
                ('ent_content', models.TextField()),
                ('ent_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollLatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_headlines', models.TextField()),
                ('latest_content', models.TextField()),
                ('latest_image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrollWorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_headlines', models.TextField()),
                ('world_content', models.TextField()),
                ('world_image_url', models.TextField()),
            ],
        ),
    ]
