# Generated by Django 3.0.7 on 2020-08-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsHeadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.TextField()),
                ('Headlines_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Headlines')),
            ],
        ),
    ]
