# Generated by Django 3.0.7 on 2020-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.CharField(choices=[('trending', 'Trending'), ('latest', 'Latest'), ('cricket', 'Cricket'), ('entertaining', 'Entertaining'), ('rip', 'RIP'), ('india', 'India'), ('city', 'City')], max_length=100),
        ),
    ]
