# Generated by Django 3.0.7 on 2020-07-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='news_id',
        ),
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField()),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tags')),
            ],
        ),
    ]
