# Generated by Django 3.0.7 on 2020-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_ndtvcitynews_ndtvcountrynews_ndtvcricketnews_ndtventnews_ndtvlatestnews_ndtvworldnews_scrollcitynews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('trending', 'Trending'), ('latest', 'Latest'), ('cricket', 'Cricket'), ('entertaining', 'Entertaining'), ('rip', 'RIP'), ('india', 'India')], max_length=100)),
                ('news_id', models.IntegerField()),
                ('news_web', models.CharField(max_length=100)),
            ],
        ),
    ]
