# Generated by Django 3.0.7 on 2020-08-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headlines_newsheadlines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsheadlines',
            old_name='Headlines_id',
            new_name='headlines_id',
        ),
    ]
