# Generated by Django 3.0.7 on 2020-07-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='tags',
        ),
    ]
