# Generated by Django 3.0.7 on 2020-08-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200814_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstag',
            name='tag_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='news.Tags'),
        ),
    ]
