# Generated by Django 3.0.7 on 2020-08-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200814_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstag',
            name='news_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='tag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Tags'),
        ),
    ]
