# Generated by Django 3.0.7 on 2020-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200814_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsheadlines',
            name='news_id',
            field=models.IntegerField(),
        ),
    ]
